# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a1f27ec6f0b3fe6d35f597150b820852ddd310fdbc63bf14872b664f7a343757186cdab6229a3e4463f3410f7cf636727162c4d6b181770225dfb9c85591eae

test:
  secret_key_base: 110580717f776a935e0f69543fbd22d474d1384d2b0dbe190422ca42da27275068cce5d1cebcbb887d6246b4f68b7939698b35424b37e8aa70b24521629e9fe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
